import { create } from "zustand";

type CampaignObj = {
    campaignName: string;
    views: string;
    budgetSpent: string;
    status: "active" | "past" | "waitlist" | "new";
    clicks: string;
    reward: string;
    campaignDetails: string;
    audienceLocationPreference: string;
    contentType: string;
    language: string;
    platform: string;
    logo: File | null;
    acceptanceCriteria: "automatic" | "manual";
    budget: string;
    revenuePerView: string;
    startDate: string;
    endDate: string;
    uploadedContent: File | null;
};

type Campaigns = CampaignObj[];

type SetDetailedCampaign = (detailedCampaign: CampaignObj) => void;

type CreateCampaign = (newCampaign: CampaignObj) => void;

type UseBrandCampaigns = {
    campaigns: Campaigns;
    createCampaign: CreateCampaign;
    detailedCampaign: CampaignObj;
    setDetailedCampaign: SetDetailedCampaign;
};

const useBrandCampaigns = create<UseBrandCampaigns>((set) => ({

    campaigns: [
        
        {
            campaignName: 'Brand Takeover',
            views: '2578',
            budgetSpent: '$2458',
            status: 'active',
            clicks: "2k",
            reward: "$10.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Ant/ Rippy Club Clips',
            views: '6550',
            budgetSpent: '$4000',
            status: 'active',
            clicks: "1k",
            reward: "$5.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Mufi Campaign',
            views: '4657',
            budgetSpent: '$3578',
            status: 'active',
            clicks: "3k",
            reward: "$15.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Angry Birds',
            views: '8650',
            budgetSpent: '$7567',
            status: 'active',
            clicks: "5k",
            reward: "$25.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Influencer Takeover',
            views: '2578',
            budgetSpent: '$2458',
            status: 'active',
            clicks: "2k",
            reward: "$10.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Ant/ Rippy Club Clips',
            views: '6550',
            budgetSpent: '$4000',
            status: 'active',
            clicks: "1k",
            reward: "$5.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Mufi Campaign',
            views: '4657',
            budgetSpent: '$3578',
            status: 'active',
            clicks: "3k",
            reward: "$15.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Angry Birds',
            views: '8650',
            budgetSpent: '$7567',
            status: 'active',
            clicks: "5k",
            reward: "$25.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Audience Test',
            views: '6550',
            budgetSpent: '$4000',
            status: 'past',
            clicks: "1k",
            reward: "$5.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Demographic Test',
            views: '2578',
            budgetSpent: '$2458',
            status: 'past',
            clicks: "2k",
            reward: "$10.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Location Test',
            views: '4657',
            budgetSpent: '$3578',
            status: 'past',
            clicks: "3k",
            reward: "$15.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Demographic Test',
            views: '2578',
            budgetSpent: '$2458',
            status: 'past',
            clicks: "2k",
            reward: "$10.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Location Test',
            views: '4657',
            budgetSpent: '$3578',
            status: 'past',
            clicks: "3k",
            reward: "$15.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Influencer Takeover',
            views: '2578',
            budgetSpent: '$2458',
            status: 'waitlist',
            clicks: "2k",
            reward: "$10.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Ant/ Rippy Club Clips',
            views: '6550',
            budgetSpent: '$4000',
            status: 'waitlist',
            clicks: "1k",
            reward: "$5.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Demographic Test',
            views: '2578',
            budgetSpent: '$2458',
            status: 'waitlist',
            clicks: "2k",
            reward: "$10.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Location Test',
            views: '4657',
            budgetSpent: '$3578',
            status: 'waitlist',
            clicks: "3k",
            reward: "$15.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Influencer Takeover',
            views: '2578',
            budgetSpent: '$2458',
            status: 'new',
            clicks: "2k",
            reward: "$10.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Ant/ Rippy Club Clips',
            views: '9578',
            budgetSpent: '$5000',
            status: 'new',
            clicks: "1k",
            reward: "$5.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
        {
            campaignName: 'Location Test',
            views: '4657',
            budgetSpent: '$3578',
            status: 'new',
            clicks: "3k",
            reward: "$15.00",
            campaignDetails: "",
            audienceLocationPreference: "",
            contentType: "",
            language: "",
            platform: "",
            logo: null,
            acceptanceCriteria: "automatic",
            budget: "",
            revenuePerView: "",
            startDate: "",
            endDate: "",
            uploadedContent: null,
        },
    ],

    createCampaign: (newCampaign) => {
        set((state) => ({
            ...state,
            campaigns: [...state.campaigns, newCampaign]
        }))
    },

    detailedCampaign: {
        campaignName: "",
        views: "",
        budgetSpent: "",
        status: "new",
        clicks: "",
        reward: "",
        campaignDetails: "",
        audienceLocationPreference: "",
        contentType: "",
        language: "",
        platform: "",
        logo: null,
        acceptanceCriteria: "automatic",
        budget: "",
        revenuePerView: "",
        startDate: "",
        endDate: "",
        uploadedContent: null,
    },

    setDetailedCampaign: (curCampaign) => {
        set((state) => ({
            ...state,
            detailedCampaign: curCampaign,
        }));
    },
}));

export default useBrandCampaigns;